# Site settings
title: Jay Holman
email: brickfort2013@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An TOTALLY AWESOME DESCRIPTION.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jayholman.xyz" # the base hostname & protocol for your site
twitter_username: brickfort
github_username:  jayholman

# Build settings
markdown: kramdown
