# Site settings
title: Jay Holman
email:
description: > # this means to ignore newlines until "baseurl:"
  Adventure, coupled with Adventure, and then a little dash more of Adventure.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jayholman.xyz" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
